# Generated by Django 5.1.2 on 2024-12-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_alter_prediction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopair',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='cryptopair',
            unique_together={('symbol', 'timeframe')},
        ),
    ]
